.Dd 2/4/09               \" DATE 
.Dt mirror 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm mirror,
.Nd a program to mirror displays on Apple's Mac OS X.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl h
.Op Fl t
.Op Fl on
.OpFl off
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm Is a program to mirror displays on Apple's Mac OS X.
.Pp
A list of flags and their descriptions:
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It Fl h                 \"-h flag as a list item
Print usage and exit.
.It Fl t
Toggle mirroring (default behavior)
.It Fl on
Turn Mirroring On
.It Fl off
Turn Mirroring Off
.El                      \" Ends the list
.Pp
.Sh BUGS              \" Document known, unremedied bugs 
Passing more than one argument causes undefined behavior. It is illogical to do so.
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
